image: registry.gitlab.com/wldhx/ouifennec:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-image:
  stage: build
  tags:
    - shell
  when: manual
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  tags:
    - docker
  script:
    - ./build.sh
