image: registry.gitlab.com/equalitie/ouifennec:bootstrap

stages:
  - build-image
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-image:
  stage: build-image
  tags:
    - shell
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --target bootstrap -t $CI_REGISTRY_IMAGE:bootstrap .
    - docker push $CI_REGISTRY_IMAGE:bootstrap

build:
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - gecko-dev/obj-arm-linux-androideabi/dist/ceno-66.0.3.en-US.android-arm.apk
  script:
    - ./build.sh
