image: wldhx/ouifennec-ci:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-image:
  stage: build
  tags:
    - shell
  when: manual
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE:latest

build:
  tags:
    - docker
  script:
    - ./build.sh
