image: registry.gitlab.com/equalitie/ouifennec:latest

stages:
  - build-image
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-image:
  stage: build-image
  tags:
    - shell
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:latest - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - gecko-dev/obj-arm-linux-androideabi/dist/ceno-66.0.3.en-US.android-arm.apk
  script:
    - ./build.sh

    - echo "$GRADLE_PROPERTIES_BASE64" > /dev/shm/gradle.properties
    - echo "$UPLOAD_KEYSTORE_BASE64" > /dev/shm/upload-keystore.jks
    - export GRADLE_USER_HOME=/dev/shm
    - ./build.sh -r
