stages:
  - build-image
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_BUILDKIT: 1

build-image:
  stage: build-image
  only:
    changes:
      - gecko-dev/build/
      - ouinet/
      - Dockerfile
  tags:
    - shell
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:bootstrap .
    - docker push $CI_REGISTRY_IMAGE:bootstrap

build:
  stage: build
  tags:
    - shell
  script:
    - mkdir -p root.build/.cache/ root.build/.ccache/ /dev/shm/.android/
    - echo "$CENO_DEBUG_KEYSTORE" | base64 -d - > debug.keystore
    - touch gecko-dev/mozconfig
    - docker run --rm --user $(id -u):$(id -g) --mount type=bind,source="$(pwd)",target=/usr/local/src/ouifennec --mount type=bind,source="$(pwd)/root.build/.cache",target=/mnt/home/.cache --mount type=bind,source="$(pwd)/root.build/.ccache",target=/mnt/home/.ccache $CI_REGISTRY_IMAGE:bootstrap ./build.sh
  cache:
    key: single
    paths:
      - root.build/
