stages:
  - build-image
  - build-user-image
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_BUILDKIT: 1

build-image:
  stage: build-image
  only:
    changes:
      - gecko-dev/build/
      - ouinet/
      - Dockerfile
  tags:
    - shell
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:bootstrap .
    - docker push $CI_REGISTRY_IMAGE:bootstrap

build-user-image:
  stage: build-user-image
  tags:
    - shell
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - >
      docker build --pull
      --build-arg USER_UID=$(id -u) --build-arg USER_GID=$(id -g)
      -t $CI_REGISTRY_IMAGE:bootstrap-$USER - < Dockerfile.user
    - docker push $CI_REGISTRY_IMAGE:bootstrap-$USER

build:
  stage: build
  tags:
    - shell
  # Please note that running an APK built with the default `ouinet.xml` configuration
  # is quite pointless, but it may help you check that the build succeeds.
  script:
    - mkdir -p _cache/_android _cache/_ccache _cache/_gradle
    - mkdir -p fennec && touch fennec/.finished-bootstrap
    - echo "$CENO_DEBUG_KEYSTORE" | base64 -d > fennec/debug.keystore
    - echo "$CENO_DEBUG_KEYSTORE_PASSWORD" | base64 -d > fennec/debug.keystore-passwords
    - if [ "$OUINET_VALUES_XML" ]; then cp "$OUINET_VALUES_XML" fennec/ouinet.xml; fi
    - >
      docker run
      --rm --user $(id -u):$(id -g)
      --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined
      --mount type=bind,source="$(pwd)",target=/usr/local/src/ouifennec
      --mount type=bind,source="$(pwd)/_cache",target=/root/.cache
      $CI_REGISTRY_IMAGE:bootstrap-$USER
      ./build.sh ${OUINET_VALUES_XML:+-x fennec/ouinet.xml}
  artifacts:
    paths:
      - "*.aar"
      - "*.apk"
    expire_in: 6h
  cache:
    key: single
    paths:
      - root.build/
